---
name: Build Backend NextJS Project

on:
  push:
    branches-ignore:
      - release
      - main
      - develop

  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:

jobs:
  build-frontend:
    name: Build Frontend Static Website
    runs-on: ubuntu-latest
    steps:
      - run: echo 'event name is:' ${{ github.event_name }}
      - run: echo 'event type is:' ${{ github.event.action }}
      - name: "ğŸ“¥  checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "ğŸ”  Verify Changed Backend NextJS"
        uses: tj-actions/changed-files@v23.1
        id: changed-backend-nextjs
        with:
          files: |
              backend/project/**/*

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-backend-nextjs.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: "ğŸ”„  Cache node_modules"
        if: steps.changed-backend-nextjs.outputs.any_changed == 'true'
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: "ğŸ”§  Setup NodeJS 14.20.1"
        if: steps.changed-backend-nextjs.outputs.any_changed == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: 14.20.1

      - name: "ğŸ”§  Install npm@latest"
        if: steps.changed-backend-nextjs.outputs.any_changed == 'true'
        run: npm i -g npm@latest

      - name: "ğŸ“¦  Install Backend NextJS"
        if: steps.changed-backend-nextjs.outputs.any_changed == 'true'
        run: |
          bash scripts/backend/project/ci-install.bash

      - name: "ğŸ”  Lint Frontend Static Website"
        if: steps.changed-backend-nextjs.outputs.any_changed == 'true' && github.event_name == 'push'
        run: bash scripts/backend/project/lint.bash

      - name: 'ğŸ§ª  Test Frontend Living Style Guide'
        if: steps.changed-backend-nextjs.outputs.any_changed == 'true' && github.event_name == 'push'
        run: bash scripts/backend/project/test.bash

      - name: "ğŸ—ï¸  Build Frontend Static Website"
        if: steps.changed-backend-nextjs.outputs.any_changed == 'true' && github.event_name == 'pull_request'
        run: |
          bash scripts/backend/project/build.bash production